'use client'

import { useState } from 'react'
import { Card } from '@/components/ui'
import { ChevronDown, ChevronUp, HelpCircle, Mail, MessageCircle } from 'lucide-react'

const FAQS = [
  {
    q: 'How do I make a deposit?',
    a: 'To make a deposit, click "Deposit Funds" on your dashboard. Select your cryptocurrency, enter the desired amount, and submit the request. Our admin team will review and approve your deposit within 24 hours. You will receive a confirmation once it is processed.',
  },
  {
    q: 'How long do withdrawals take?',
    a: 'Withdrawal requests are typically processed within 24–48 business hours. Once approved by our admin team, funds are sent directly to your provided wallet address. Processing times may vary depending on blockchain congestion.',
  },
  {
    q: 'What cryptocurrencies do you support?',
    a: 'VaultX currently supports Bitcoin (BTC), Ethereum (ETH), Tether (USDT), Binance Coin (BNB), Solana (SOL), and Ripple (XRP). We are continually evaluating additional assets to add to our platform.',
  },
  {
    q: 'Is my investment insured?',
    a: 'VaultX employs industry-standard security measures including cold storage for a majority of funds, multi-factor authentication, and real-time monitoring. While we take every precaution, cryptocurrency investments inherently carry risk and are not FDIC insured.',
  },
  {
    q: 'How is my profit calculated?',
    a: 'Profit is calculated based on the returns generated by your invested portfolio over time. Our investment strategies are managed by experienced traders, and profits are reflected in your dashboard stats. ROI is shown as a percentage of your total deposited amount.',
  },
]

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false)

  return (
    <div className="border-b border-border-default last:border-b-0">
      <button
        onClick={() => setOpen((v) => !v)}
        className="w-full flex items-center justify-between gap-4 py-4 text-left group"
      >
        <span className="text-text-primary font-medium text-sm group-hover:text-accent-gold transition-colors">
          {q}
        </span>
        {open ? (
          <ChevronUp className="w-4 h-4 text-accent-gold shrink-0" />
        ) : (
          <ChevronDown className="w-4 h-4 text-text-muted shrink-0 group-hover:text-accent-gold transition-colors" />
        )}
      </button>
      {open && (
        <p className="text-text-muted text-sm pb-4 leading-relaxed pr-8">{a}</p>
      )}
    </div>
  )
}

export default function SupportPage() {
  return (
    <div className="space-y-6 max-w-2xl">
      <div>
        <h1 className="text-2xl font-display font-bold text-text-primary">Support Center</h1>
        <p className="text-text-muted text-sm mt-1">Frequently asked questions and contact information</p>
      </div>

      {/* FAQ */}
      <Card variant="default">
        <div className="flex items-center gap-2 mb-5">
          <HelpCircle className="w-5 h-5 text-accent-gold" />
          <h2 className="text-base font-semibold text-text-primary">Frequently Asked Questions</h2>
        </div>
        <div>
          {FAQS.map((faq, i) => (
            <FAQItem key={i} q={faq.q} a={faq.a} />
          ))}
        </div>
      </Card>

      {/* Contact card */}
      <Card variant="gold">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-start gap-3">
            <div className="w-10 h-10 rounded-lg bg-accent-gold/10 flex items-center justify-center shrink-0">
              <MessageCircle className="w-5 h-5 text-accent-gold" />
            </div>
            <div>
              <h3 className="text-text-primary font-semibold text-sm">Still need help?</h3>
              <p className="text-text-muted text-sm mt-0.5">
                Our support team is here 24/7 to assist you.
              </p>
            </div>
          </div>
          <a
            href="mailto:support@vaultx.com"
            className="flex items-center gap-2 px-5 py-2.5 rounded-lg bg-accent-gold text-bg-primary font-semibold text-sm hover:bg-accent-gold/90 transition-colors whitespace-nowrap"
          >
            <Mail className="w-4 h-4" />
            support@vaultx.com
          </a>
        </div>
      </Card>
    </div>
  )
}
